### ISSUE TITLE
Installing MacOSX Wheel under Conda using PIP fails to install

### ISSUE THREAD

**Issue by davethejoy** [Esri/pyprt#25]
```
(base) ~ % pip install https://github.com/Esri/pyprt/files/4593213/PyPRT-1.0.0-cp37-cp37m-macosx_10_15_x86_64.whl.zip
Collecting https://github.com/Esri/pyprt/files/4593213/PyPRT-1.0.0-cp37-cp37m-macosx_10_15_x86_64.whl.zip
  Downloading https://github.com/Esri/pyprt/files/4593213/PyPRT-1.0.0-cp37-cp37m-macosx_10_15_x86_64.whl.zip (18.7 MB)
     |████████████████████████████████| 18.7 MB 2.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/dave.lajoie/Miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/90/2zp9njmn29g3ztv7drth0mzr0000gp/T/pip-req-build-xqkwpp_k/setup.py'"'"'; __file__='"'"'/private/var/folders/90/2zp9njmn29g3ztv7drth0mzr0000gp/T/pip-req-build-xqkwpp_k/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/90/2zp9njmn29g3ztv7drth0mzr0000gp/T/pip-req-build-xqkwpp_k/pip-egg-info
         cwd: /private/var/folders/90/2zp9njmn29g3ztv7drth0mzr0000gp/T/pip-req-build-xqkwpp_k/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/dave.lajoie/Miniconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/90/2zp9njmn29g3ztv7drth0mzr0000gp/T/pip-req-build-xqkwpp_k/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mistafunk** [comment]
you probably need to first unzip the wheel manually, i had to zip it to be able to attach it to github

**Comment by davethejoy** [comment]
silly me! it works.

**Comment by davethejoy** [comment]
Tx!
